### ISSUE TITLE
Simplify building with an optional feature gate?

### ISSUE THREAD

**Issue by gwihlidal** [Twinklebear/ispc-rs#6]
Hi Will,

I recently released the intel_tex crate, which provides support for Intel's ISPC texture compressor.

During the development, I came across a couple annoying issues I documented here: https://github.com/gwihlidal/intel-tex-rs/issues/2

End users of the crate require both ISPC in the path, and also libclang installed or in the PATH, since ispc-rs uses bindgen to generate rust bindings at build time. I think this could greatly be improved by modifying ispc-rs to support (via an optional feature gate) the ability to generate bindings on demand, and saving them into the src tree instead of the out dir (specified on the ispc config object in build.rs). Users of a crate containing ispc files (i.e. intel_tex) would never run bindgen, instead just rely on the bindings pre-created and submitted to the repository as source code. When I make changes to the ISPC kernels, I would then build with the feature gate enabled that would produce updated bindings.

Requiring ISPC in the path is unfortunate for end users of the crate (that aren't modifying the actual ISPC kernels). This is a packaging issue, and I have a few ideas around this, but it would be great to get the bindgen dependency addressed first.

Do you think this is feasible, or have another idea?

Thank you!
Graham

**Comment by Twinklebear** [comment]
Hey Graham,

The `intel_tex` crate looks great! I think this should be possible to do, and would make the ispc crate much more useful, by allowing crates which use ISPC but don't want to push ispc/clang/bindgen as dependencies onto their users.

I think to do this I could split the ispc-rs crate into a compile time and runtime crate, and add support for multiple `--target` attributes to allow runtime selection of the vector-width code. The latter feature is already supported by ispc, but ispc-rs needs to add support for building and linking against the multiple vector-isa object files.

To remove the runtime bindgen and libclang dependencies (and even ispc), the crate can be split into a compile time and runtime crate. Then only the build script would need the compile time crate, which would have the ispc, libclang and bindgen dependencies to build the ispc library, bindings, and link the library. The runtime crate would just have the task system and instrumentation parts. This should actually lighten the runtime dependencies of crates using ispc by quite a lot too. To actually avoid pushing the dependencies onto the end user, the ispc compilation part using the compile time crate can be put behind a feature gate, or into an internal crate of the library.

The library writer's work will get a bit more complicated to manage the packaging of the ISPC crates, but ispc-rs can help some. Since the user won't be building the ispc code, the library writer will have to package compiled versions for the different OS targets, and still include some kind of build script to pick and link the right one. So what might work is to have the build script push the ispc compilation behind a feature gate, or move it to a sub-crate internal to the library. Then when building without the feature gate, or linking the main crate, it would use the existing bindings and the build script would pick the right compiled binary to link (i.e., Windows, Linux, Mac). If someone wants to follow the old path and still require the dependencies on the end user side they could just have a single crate w/o the feature gating to disable building the ispc code.

Then adding the support for multiple targets will give some extra portability for free, from ispc's built in feature detection and vector-isa picking, without needing additional work from the crate.

I think the structure for the `intel_tex` crate would then end up kind of like this:

- Push the ispc compilation and compile time library linking behind a feature gate in the build script. To build the binaries for each platform, you'd then have to build this crate on Windows, Linux and Mac and can just take the generated bindings from one of these builds to distribute. This could also be done in some internal crate, but it will have the same result.

- Then, using the ispc runtime crate you'd write your end-user facing library which would then use the packaged libraries and bindings file built in the previous step. The ispc runtime library would include some build script utilities to pick the right library for the OS to link against to help make this a bit easier.

The process is a bit involved, but it mostly comes from the need to make the binaries for the users, if they won't be building it themselves.

How does this sound?

**Comment by Twinklebear** [comment]
It looks like the multiple ISA target support I already had in there, but didn't have any example of how it worked. I changed the aobench example to show it off 62500b54ced10f54d7b9d3a6549182acddf1b6a7

**Comment by gwihlidal** [comment]
Sorry for the late reply.

This is great! Exactly what I was looking for.

I'll give this a shot in the intel_tex crate and let you know how it goes.

**Comment by Twinklebear** [comment]
No problem! I tried out implementing support for this in https://github.com/gwihlidal/intel-tex-rs/pull/3 , but I haven't tested some portability stuff, like compiling with all ISAs and then taking the binaries to a machine with just SSE4, or different linux/windows machines.

Let me know if you run into any issues
